package Slice

import (
	"github.com/Synertry/GoSysUtils/Str"
)

// GenRandomStrings generates a slice of random strings with the given length.
// The strings are generated by Str.GenRandom.
// The length of each string is increasing by (i+1/2) with i being the passed length.
func GenRandomStrings(length int) []string {
	slice := make([]string, length)
	for i := 0; i < length; i++ {
		slice[i] = Str.GenRandom((i + 1) / 2)
	}
	return slice
}

// GenRandomStringsLen generates a slice of strings with the given length lenSlice.
// The strings are generated by Str.GenRandom.
// The length of each string is defined by the passed lenString.
// This makes it possible to generate a slice of letters:
// Example: GenRandomStringsLen(5, 1) -> ["a", "c", "e", "g", "i"]
// or a slice of strings with the same length:
// Example: GenRandomStringsLen(5, 3) -> ["gea", "brv", "pgd", "qwo", "cie"]
func GenRandomStringsLen(lenSlice, lenString int) []string {
	slice := make([]string, lenSlice)
	for i := 0; i < lenSlice; i++ {
		slice[i] = Str.GenRandom(lenString)
	}
	return slice
}
